<div class='news_item'><a href='[field:arcurl/]'>
              <div class='news_item_img'><img src='[field:picname/]' /></div>
              <div class='news_item_con'>
                <div class='news_item_title'>[field:title/]</div>
                <div class='news_item_des'>[field:description function="cn_substr(@me,200)"/]...<br/>
                  <br/>
                </div>
              </div>
              </a></div>