<?php
$z[0]=Array("channelartlist","\r\n    <div class=\"help_list\">\r\n      <div class=\"help_top\">\r\n        <h3>{dede:field name='typename'/}</h3>\r\n        <span></span></div>\r\n      <ul>\r\n        {dede:channel type='son' noself='yes'}\r\n        <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n        {/dede:channel}\r\n      </ul>\r\n    </div>\r\n    ",43,426);
$z[0][4]=array();
$z[0][4]['typeid']="top";
$z[0][4]['row']="4";
$z[1]=Array("global","",718,744);
$z[1][4]=array();
$z[1][4]['name']="cfg_powerby";
$z[2]=Array("global","",757,781);
$z[2][4]=array();
$z[2][4]['name']="cfg_beian";
$z[3]=Array("global","",842,864);
$z[3][4]=array();
$z[3][4]['name']="cfg_tel";
$z[4]=Array("type"," <a href=\"[field:typelink/]\"><span class=\"icon-globe\"></span>[field:typename/]</a>",1079,1195);
$z[4][4]=array();
$z[4][4]['typeid']="1";
$z[5]=Array("global","",1241,1263);
$z[5][4]=array();
$z[5][4]['name']="cfg_tel";
$z[6]=Array("type"," <a href=\"[field:typelink/]\"><span class=\"icon-user\"></span>联系</a>",1339,1444);
$z[6][4]=array();
$z[6][4]['typeid']="12";
$z[7]=Array("global","",1733,1754);
$z[7][4]=array();
$z[7][4]['name']="cfg_qq";
$z[8]=Array("global","",1951,1972);
$z[8][4]=array();
$z[8][4]['name']="cfg_qq";
$z[9]=Array("global","",2198,2220);
$z[9][4]=array();
$z[9][4]['name']="cfg_tel";
$z[10]=Array("global","",2284,2308);
$z[10][4]=array();
$z[10][4]['name']="cfg_phone";

?>